### PR TITLE
Wolverino

### PR DESCRIPTION
**Pull request by hugoslv**

### CODE REVIEW

**Comment by suskind** [comment]
Your project will be __5__  Your project file will be renamed to __project_5-wolverino.md__ 
Please, use your project number to identify your video and project from now on. 

BTW, pay attention, you have deleted all content of our nobull_bot.md. It is updated again.

**Comment by suskind** [comment]
And... there are two team members without their Pixels Camp profile URL. Please, update it

**Comment by hugoslv** [comment]
I don’t thing that they’ve registered as a participant but both are with BEE Very Creative (partner)… can they still register?

**Comment by suskind** [comment]
Yes, no problem. 
Thank you

**Pull request merged**
